---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-service-account
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name:  broker-webapp
  labels:
    app:  broker-webapp
spec:
  type: LoadBalancer
  ports:
  - port:  8080
    targetPort: 8080
    name: http
  selector:
    app:  broker-webapp
---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      bb: web
  replicas: 1
  template:
    metadata:
      labels:
        bb: web
    spec:
      serviceAccount: client-service-account
      containers:
        - name: broker-webapp
          image: nishantapatil3/broker-webapp:latest
          command: ["/bin/sleep","infinity"]
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
            readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
metadata:
  name: "broker-webapp"
  namespace: default

