--- 
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: client-service-account
  namespace: default 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name:  helloworld-example 
  labels: 
    app:  helloworld-example 
    nsm/role: client 
spec: 
  type: LoadBalancer
  ports: 
  - port:  8080
    targetPort: 8080
    nodePort: 30036
    name: http 
  selector: 
    app:  helloworld-example 
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name:  helloworld-example 
  labels: 
    version: v1 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app:  helloworld-example 
      version: v1 
  template: 
    metadata: 
      labels: 
        app:  helloworld-example 
        version: v1 
    spec: 
      serviceAccount: client-service-account 
      containers: 
      - name: helloworld 
        image: nishantapatil3/broker-webapp:latest
        command: ["/usr/local/bin/broker-webapp","infinity"] 
        resources: 
          requests: 
            cpu: "100m" 
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /run/spire/sockets
          name: spire-agent-socket
          readOnly: true
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
