---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-service-account
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name:  stock-quotes-service
  labels:
    app:  stock-quotes-service
spec:
  type: LoadBalancer
  ports:
  - port:  8090
    targetPort: 8090
    name: http
  selector:
    app:  stock-quotes-service
---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      bb: web
  replicas: 1
  template:
    metadata:
      labels:
        bb: web
    spec:
      serviceAccount: server-service-account
      containers:
        - name: stock-quotes-service
          image: nishantapatil3/stock-quotes-service:latest
          command: ["/usr/local/bin/stock-quotes-service","infinity"]
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /run/spire/sockets
            name: spire-agent-socket
            readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
metadata:
  name: "stock-quotes-service"
  namespace: default
