apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {{ .Values.addressPrefix }}.{{ .Values.globalPrefix }}.1-{{ .Values.addressPrefix }}.{{ .Values.globalPrefix }}.250

