name: Release

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.14

    - name: Build
      run: make build
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push - broker-webapp
      uses: docker/build-push-action@v3
      with:
        file: ./docker/broker-webapp/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/broker-webapp:latest
    - name: Build and push - stock-quotes-service
      uses: docker/build-push-action@v3
      with:
        file: ./docker/stock-quotes-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/stock-quotes-service:latest
